### ISSUE TITLE
items not in any tabs

### ISSUE THREAD

**Issue by Redd56** [hm-ysjiang/usefulstuff#3]
glue isnt in creative tabs anywhere :p
dont know how that slipped happened lol

**Comment by Redd56** [comment]
i think my commit should fix it, if it doesnt its easy to revert and im bad at java

**Comment by Redd56** [comment]
also tflipflops arent in any creative tab

**Comment by hm-ysjiang** [comment]
Uh, I see...
I changed the method that items/blocks used to register into the game when I am doing the config disable thingy, and I totally forgot the creative tab. Basically, all of the items that use the new method disappeared from the tab.
I think I'll fix it my side within the next commit since it will be a bit of mess to change every item/block file.

Sorry for not merging your PR, but I truly appreciate your report. 👍

**Comment by Redd56** [comment]
Its fine. But just out of curiosity eould that have worked? Im not good at coding rn lol

**Comment by Redd56** [comment]
Also thats a good idea lol

**Comment by hm-ysjiang** [comment]
In [ModItems.java](https://github.com/hm-ysjiang/usefulstuffs/blob/master/src/main/java/hmysjiang/usefulstuffs/init/ModItems.java), I have a static method that takes the registry instance to register the items and add them to the tab. But in 56a73afb3f8aeb08bb13de49918d2e7a352be7dc I register the items directly to the registry, and that's why the items are not in the tab.

**Comment by Redd56** [comment]
But woild it have? Im new to coding mods

**Comment by hm-ysjiang** [comment]
@Redd56 Yes, in [ModItems.java, line 222](https://github.com/hm-ysjiang/usefulstuffs/blob/master/src/main/java/hmysjiang/usefulstuffs/init/ModItems.java#L222)
